### ISSUE TITLE
Weight chart stopped showing, now is empty

### ISSUE THREAD

**Issue by cangeeq** [nextcloud/health#64]
The weight chart recently disappeared for me.

When I go to Health -> Weight initially the Chart heading is shown but there is no chart.

If I go to the Weight settings and disabled and re-enabled the Weight column, the chart reappears, but the y-axis is scaled only from 0 to 1.0 and no weights were showing (I'm not heavy, but I'm not _that_ light. :-) ).

I also tried disabling / re-enabling the Weight module, and uninstalling / re-installing the app.

No errors in the logs.

App version shows as 1.1.0 (which I don't even see in Releases / Tags?), Nextcloud 20.0.9, 7.2.24-0ubuntu0.18.04.7

**Comment by jaywink** [comment]
Same here, I can see this error in the browser console:

```
[Vue warn]: Error in render: "TypeError: def.getValueY is not a function"

found in

---> <Chart> at src/general/Chart.vue
       <WeightChart> at src/modules/weight/WeightChart.vue
         <WeightContent> at src/modules/weight/WeightContent.vue
           <AppContent>
             <Content>
               <App> at src/App.vue
                 <Root>
```

App version also 1.1.0. This broke with the latest update, a few days ago?

**Comment by datenangebot** [comment]
Hi, thanks for the reports. I can confirm the error. In my Setup broken too 😎

I will fix that soon.

**Comment by car-gli** [comment]
Same problem here, but slightly different.
Everything was OK as long I was on NC 20, After upgrade to 21, app was not supoted anymore.
Now got the new version, but no chart anymore 
![2021-04-22_18-57-57](https://user-images.githubusercontent.com/22268258/115711301-8d416c00-a39d-11eb-969f-ab5aa945ad8a.png)
